### ISSUE TITLE
[BUG] bug with GET /your_index/_search and POST _reindex in OS 2.11

### ISSUE THREAD

**Issue by LandryK** [opensearch-project/neural-search#626] opened 2024-03-07 17:36 UTC
### What is the bug?
When you configure an index with a search pipeline as below  the 
 `GET /your_index/_search ` yields a 500 error - Null Pointer Exception. 
It seems like by default the `_reindex` API uses the  `GET /your_index/_search ` as such if you attempt to perform re-index with a source_index that has a `index.search.default_pipeline` configured you will get a Null Pointer Exception. 

```
POST _reindex
{
   "source":{
      "index":"source-index"
   },
   "dest":{
      "index":"destination-index",
      "pipeline": "your-pipeline"
   }
}`
### How can one reproduce the bug?

1- Create Pipeline:
`PUT /_search/pipeline/test-pipeline
{
  "request_processors": [
    {
      "neural_query_enricher" : {
        "tag": "tag1",
        "description": "your description",
        "default_model_id": "your_model_id"
      }
    }
  ]
}

```

2- Create index with pipeline and setup default search pipeline 
```
PUT /source-index
{
  "settings": {
    "index": {
      "knn": true,
      "knn.algo_param.ef_search": 100
    },
    "default_pipeline": "test-pipeline",
    "index.search.default_pipeline" : "test-pipeline"
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text"
      },
      "passage_embedding": {
        "type": "knn_vector",
        "dimension": 384,
        "method": {
          "name": "hnsw",
          "space_type": "l2",
          "engine": "nmslib",
          "parameters": {
            "ef_construction": 128,
            "m": 24
          }
        }
      }
    }
  }
}
```

3- add documents 
```
PUT /source-index/_doc/1
{
    "text": "The emergence of resistance of bacteria to antibiotics is a common phenomenon. Emergence of resistance often reflects evolutionary processes that take place during antibiotic therapy."
  
}
```
```
PUT /source-index/_doc/2
{
  "text": "The successful outcome of antimicrobial therapy with antibacterial compounds depends on several factors. These include host defense mechanisms, the location of infection, and the pharmacokinetic and pharmacodynamic properties of the antibacterial."
}

```

4- search (This will yield a NPE-500 error)
`GET /source-index/_search`
This will give NPE due to `"index.search.default_pipeline" : "test-pipeline"`. If you remove this setting in the index setting, the query works just fine.

5- Proceed to Create a destination index 
```
PUT /destination-index
{
  "settings": {
    "index": {
      "knn": true,
      "knn.algo_param.ef_search": 100
    },
    "default_pipeline": "test-pipeline",
    "index.search.default_pipeline" : "test-pipeline"
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text"
      },
      "passage_embedding": {
        "type": "knn_vector",
        "dimension": 384,
        "method": {
          "name": "hnsw",
          "space_type": "cosinesimil",
          "engine": "nmslib",
          "parameters": {
            "ef_construction": 128,
            "m": 24
          }
        }
      }
    }
  }
}
```

6- Attempt to perform re-indexing (This will give you a NPE - 500 error)
```
POST _reindex
{
   "source":{
      "index":"source-index"
   },
   "dest":{
      "index":"destination-index",
      "pipeline": "test-pipeline"
   }
}

```

The above will not work because `GET /source-index/_search` gives a NPE error due to the `"index.search.default_pipeline" : "test-pipeline"` as discussed in Step 4.
However if you remove the "index.search.default_pipeline" : "test-pipeline" the index settings, the query works. 

7- if you try re-index with below it works
```
POST _reindex
{
   "source":{
      "index":"source-index",
      "query": {
          "match_all": {}
      }
   },
   "dest":{
      "index":"destination-index",
      "pipeline": "test-pipeline"
   }
}

```

### Bugs: 
1- Seems like by default the `_reindex` API is using `GET /source-index/_search`  instead of `GET /your_index/_search{"query":{"match_all":{}}}` and since the former throws a Null Pointer Error, the `_reindex` also throws the same as it is unable to get the list of documents in source index. 

2- `GET /source-index/_search` does not work if the `"index.search.default_pipeline" : "test-pipeline"` is present in index setting

### OpenSearch Version 
OS 2.11

**Comment by navneet1v** [comment] 2024-04-01 06:11
@vibrantvarun can you take a look into this issue. Seems like some issue with NeuralQueryEnricher processor

**Comment by LandryK** [comment] 2024-04-15 21:41
@vamshin @vibrantvarun Any updates on this?
Thanks

**Comment by owaiskazi19** [comment] 2024-11-13 00:48
I tested it out. There's no null check below
https://github.com/opensearch-project/neural-search/blob/7368edcfd36c4a7d703d092fc2f73fa6c82f1d92/src/main/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessor.java#L71

causing the NPE. It was handled in https://github.com/opensearch-project/neural-search/pull/615. Should resolved the issue. @martin-gaievski @vibrantvarun can you verify and we can close this one out?

**Comment by martin-gaievski** [comment] 2024-11-13 02:01
Good catch, that PR should fix the issue. I'll run the test and update here whether or not we're good to close the issue.

**Comment by owaiskazi19** [comment] 2024-11-25 18:43
@martin-gaievski did you get a chance to verify this?

**Comment by martin-gaievski** [comment] 2024-11-26 02:11
I think info about ingest pipeline is missing in provided steps. Document ingestion will not work without that pipeline because it's needed to create embeddings.

My understanding is that we need to add following details to provided steps:

create ingest pipeline step:

```
PUT {{base_url}}/_ingest/pipeline/ingest-pipeline
{
    "description": "An NLP ingest pipeline",
    "processors": [
        {
            "text_embedding": {
                "model_id": "<model_id>",
                "field_map": {
                    "text": "passage_embedding"
                }
            }
        }
    ]
}
``` 

then put it as default pipeline for both indexes, e.g. This is needed because `default_pipeline` is of type ingest, not search.

```
PUT {{base_url}}/source-index
{
    "settings": {
        "index": {
            "knn": true,
            "knn.algo_param.ef_search": 100
        },
        "default_pipeline": "ingest-pipeline",
        "index.search.default_pipeline": "test-pipeline"
    },
    "mappings": {
        "properties": {
            "text": {
                "type": "text"
            },
            "passage_embedding": {
                "type": "knn_vector",
                "dimension": 384,
                "method": {
                    "engine": "lucene",
                    "space_type": "l2",
                    "name": "hnsw"
                }
            }
        }
    }
}
```

similarly it should ingest pipeline in the reindex request:

```
POST {{base_url}}/_reindex
{
   "source":{
      "index":"source-index"
   },
   "dest":{
      "index":"destination-index",
      "pipeline": "ingest-pipeline"
   }
}
``` 

If I do all this, then reindex operation works for me. Tested on latest 2.x (2.18)

@LandryK, please review my assessment and correct me if I'm wrong. Based on @owaiskazi19's finding, I believe this issue stems from either an incomplete configuration or a fixed scenario.

**Comment by heemin32** [comment] 2024-12-26 19:32
Seems the issue is fixed on the latest version. Please reopen it if the issue still exist.

**Closed by heemin32** 2024-12-26 19:32 UTC
Labels: bug, good first issue
