### ISSUE TITLE
[BUG] error on complex types `list type field [category] has empty string, cannot process it`

### ISSUE THREAD

**Issue by toyaokeke** [opensearch-project/neural-search#678] opened 2024-04-09 18:03 UTC
Initial bug reported in https://github.com/opensearch-project/ml-commons/issues/2303

**What is the bug?**
I am creating a text embedding processor that creates vectors on a nested field. However, I receive `illegal_argument_exception` because not all the fields in the object meet the requirement
- string
- map
- string list

Here is the explanation from the AWS support specialist
> Our internal team informed me that this exception happened when the “id” under “brand” field has int value that is not supported by the text embedding processor from ingestion pipeline, and the fields inside the complex type must be of types: string, map or list.

However, I am not creating vectors on `id` so I don't understand why it must follow these requirements. Is this expected behaviour or is this a bug?

**How can one reproduce the bug?**
1. create ingest pipeline
```bash
PUT /_ingest/pipeline/neural-search-pipeline-v2
{
  "description": "An example neural search pipeline",
  "processors": [
    {
      "text_embedding": {
        "model_id": "WeliNowB6EaQJ_XFf05V",
        "field_map": {
          "category": {
            "name": {
              "en": "category_name_vector"
            }
          }
        }
      }
    }
  ]
}
```

2. simulate ingest pipeline
```bash
POST _ingest/pipeline/neural-search-pipeline-v2/_simulate
{
  "docs": [
    {
      "_index": "neural-search-index-v2",
      "_id": "1",
      "_source": {
        "category": {
          "id": 1,
          "name": {
            "en": "category 1"
          }
        }
      }
    }
  ]
}
```

**What is the expected behavior?**
should create vectors on category name
```json
{
    "docs": [
      {
        "doc": {
          "_index": "neural-search-index-v2",
          "_id": "1",
          "_source": {
            "category": {
              "name": {
                "category_name_vector": [
                  0.019107267,
                  -0.029297447,
                  0.0070927013,
                  -0.022105217,
                  ...
                ],
                "en": "category 1"
              },
              "id": 1
            }
          },
          "_ingest": {
            "timestamp": "2024-01-08T17:59:39.543401762Z"
          }
        }
      }
    ]
  }
```

**What is your host/environment?**
 - OS: AWS Opensearch Service Managed Cluster
 - Version 2.11

**Do you have any screenshots?**
```json
{
   "failures": {
        "index": "neural-search-index-v2",
        "id": "5302821",
        "cause": {
          "type": "illegal_argument_exception",
          "reason": "list type field [category] has empty string, cannot process it"
        },
        "status": 400
   },
   ...
}
```

**Do you have any additional context?**

invalid doc
```json
{
   "brand": {
      "id": 123, // cannot be integer
      "description": {
         "en": "en description female",
         "fr": "" // cannot be empty string
      }
      ...
   },
   "category": {
      "id": "123", // valid string
      "sizes": [
         "XS",
         "XL",
         "", // elements in list cannot be empty strings
         123 // elements in list cannot be integers
         ...
      ]
   }
}
```

valid doc
```json
{
   "brand": {
      "id": "123",
      "description": {
         "en": "en description"
      }
      ...
   },
   "category": {
      "id": "123",
      "sizes": [ ] // empty list is valid
      "description": {
         // empty object is valid
      }
   }
}
```

**Comment by navneet1v** [comment] 2024-04-09 18:08
@zane-neo can you look into this issue?

**Comment by zane-neo** [comment] 2024-04-10 00:58
@toyaokeke From your example, I see two different cases: 
1. category is a map type: 
```
{
  "category": {
    "id": 1,
    "name": {
      "en": "category 1"
    }
  }
}
```
2. category doesn't have `name`.`en`: 
```
"category": {
      "id": "123",
      "sizes": [ ] // empty list is valid
   }
```

Can you confirm which case is your real production case?

**Comment by zane-neo** [comment] 2024-04-10 01:15
I did found issue in code, but the error message seems differ with yours, I created this ticket to track the issue: https://github.com/opensearch-project/ml-commons/issues/2309. Still trying to understand your case to see if there's other issues here.

**Comment by toyaokeke** [comment] 2024-04-10 02:02
> @toyaokeke From your example, I see two different cases: 
> 
> 1. category is a map type instead of list: 
> 
> ```
> 
> {
> 
>   "category": {
> 
>     "id": 1,
> 
>     "name": {
> 
>       "en": "category 1"
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 2. category doesn't have `name`.`en`: 
> 
> ```
> 
> "category": {
> 
>       "id": "123",
> 
>       "sizes": [ ] // empty list is valid
> 
>    }
> 
> ```
> 
> 
> 
> Can you confirm which case is your real production case?

Hi @zane-neo and thank you for looking into this. 

The `invalid doc` and `valid doc` examples in my description are all possible scenarios. 

- The empty strings in an array does not occur often, but is possible
- name.zh missing is also possible. Sometimes not all documents have translations for all supported languages in my production environment 
-

**Comment by toyaokeke** [comment] 2024-04-10 02:04
Also the ticket you created I also see that error as well when I run the simulator too

https://github.com/opensearch-project/ml-commons/issues/2309

**Comment by zane-neo** [comment] 2024-04-11 09:53
@toyaokeke , would like to double confirm on the `category` data structure, it's a map type instead of list, right? 
```
{
  "category": {
    "name": {
      ...
    }
  }
}
```
NOT
```
{
  "category": [
    "name": {
      ...
    }
  ]
}
```
The reason asking this is because if it's list type, it would need much more complex fix, if it's a map type the fix would be easier.

**Comment by toyaokeke** [comment] 2024-04-11 09:57
> @toyaokeke , would like to double confirm on the `category` data structure, it's a map type instead of list, right? 
> 
> ```
> 
> {
> 
>   "category": {
> 
>     "name": {
> 
>       ...
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> NOT
> 
> ```
> 
> {
> 
>   "category": [
> 
>     "name": {
> 
>       ...
> 
>     }
> 
>   ]
> 
> }
> 
> ```
> 
> The reason asking this is because if it's list type, it would need much more complex fix, if it's a map type the fix would be easier.

Correct it is a map type

**Comment by mingshl** [comment] 2024-05-07 18:28
@toyaokeke the new `ml_inference` processor support nested object type. check out this [unit test](https://github.com/opensearch-project/ml-commons/blob/f82e148210115faa30ea75c4e6084d653b825afd/plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java#L110). 

you can try using `ml_inference` processor in 2.14 version and see if that can solve your issue. https://github.com/opensearch-project/documentation-website/pull/7095 

I am still working on the tutorial for using ml inference processors using neural search query, will notice here once I have it

**Comment by toyaokeke** [comment] 2024-05-07 20:41
Hi @mingshl thank you for directing me to this! If I understand correctly this `ml_inference` processor supports nested type, but is only available in 2.14?

I am using AWS Managed Service, and it currently only supports up to 2.11. I would be more than happy to test that processor once AWS releases support for that version 🙏🏿

**Comment by toyaokeke** [comment] 2024-05-10 18:59
@mingshl considering what you shared, is this a bug that will still be fixed for the `text_embedding` processor, or are users encouraged to switch to the `ml_inference` processor for nested fields?

**Comment by toyaokeke** [comment] 2024-06-10 15:21
hello @zane-neo , I saw [this PR](https://github.com/opensearch-project/neural-search/pull/477) was recently merged. Just wanted to confirmed has a fix been merged in that case and if you have an idea which version it will be released in?

**Comment by toyaokeke** [comment] 2024-08-01 06:29
Hi @zane-neo, just checking in to see if this bug has been resolved and can be closed?

**Comment by naveentatikonda** [comment] 2024-09-18 00:54
@zane-neo can you pls validate and confirm if the bug has been fixed ? Thanks!

**Comment by toyaokeke** [comment] 2024-09-24 19:11
as part of the fix, I was also wondering if more detail could be provided in the error message? for example, which field within a nested attribute is causing the error?

for example, 
```json
{
   "failures": {
        "index": "neural-search-index-v2",
        "id": "5302821",
        "cause": {
          "type": "illegal_argument_exception",
          "reason": "list type field [category] has empty string, cannot process it"
        },
        "status": 400
   },
   ...
}
```

I do not know which field within `[category]` (e.g. name, description) is causing the error unless I look through the document myself. it would be great if the error mentioned for example

```json
{
   "failures": {
        "index": "neural-search-index-v2",
        "id": "5302821",
        "cause": {
          "type": "illegal_argument_exception",
          "reason": "[name] field within [category] entity has empty string, cannot process it"
        },
        "status": 400
   },
   ...
}

**Comment by jmazanec15** [comment] 2024-10-02 00:35
cc : @model-collapse

**Comment by zane-neo** [comment] 2024-10-09 05:52
@toyaokeke Sorry missed to update this issue, this is already fixed in this PR: https://github.com/opensearch-project/neural-search/pull/687. The root cause is when validating the map type field, the fields not shown in configuration also get validated. The fix removed the fix on those non-embedding fields, so you should not see this error and no need to worry about the field name causing the issue.

**Closed by zane-neo** 2024-10-09 05:52 UTC
Labels: bug
